### ISSUE TITLE
Hashing suggestion

### ISSUE THREAD

**Issue by kibesteve** [eric-mahasi/bank#5]
Try hashing the pin before storing it, look it up online

**Comment by eric-mahasi** [comment]
This is a great suggestion. I had considered encrypting the user data stored in the file but first I'd like to make sure that I've got the file set up and working properly. Once issue #3 is sorted out, I'll look into hashing. I'd also highly appreciate any resources you could direct me to on the same.

**Comment by kibesteve** [comment]
Ayt. Try and check out JWT authentication, in relation to this. Close the issue once done .

All the best.
